baseurl = "https://scholtzan.net/"
languageCode = "en-us"
title = "Anna Scholtz"
canonifyurls = true
PygmentsCodeFences = true
pygmentsuseclasses = false
pygmentsstyle = "colorful"
pluralizeListTitles = false
builddrafts = false


[[menu.main]]
    name = "blog"
    weight = -1
    identifier = "blog"
    url = "/blog/"
 
[[menu.main]]
    name = "about"
    weight = -2
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "travels"
    weight = 0
    identifier = "travels"
    url = "https://travel.scholtzan.net"